sudo: false
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"

# command to run tests
script: 
  - "python agr_validate.py -s gene/basicGeneInfoFile.json -d gene/wbSample.BGI.json"
  - "python agr_validate.py -s gene/basicGeneInfoFile.json -d gene/mgiSample.BGI.json"
  - "python agr_validate.py -s feature/featureMetadata.json -d feature/zfinSample.feature.json"
# whitelist
branches:
  only:
    - development
