sudo: false
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"

# command to run tests
script: 
  - "python agr_validate.py -s basicGeneInformation.json -d FB_gene_example.json"

# whitelist
branches:
  only:
    - development
