sudo: false
language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"

# command to run tests
script: 
  - "python agr_validate.py -s basicGeneInfoFile.json -d wbSample.BGI.json"
  - "python agr_validate.py -s basicGeneInfoFile.json -d mgiSample.BGI.json"

# whitelist
branches:
  only:
    - development
